#
# reference:
#   - https://lukasgeiter.github.io/mkdocs-awesome-nav/reference/
#

title: ä¸­é—´ä»¶

preserve_directory_names: true

hide: true

flatten_single_child_sections: true

ignore: "*.hidden.md"

nav:
  - æ¦‚è¿°: index.md
  - "ğŸ³ Dockerfile": dockerfile
  - "ğŸ³ Docker-compose": docker-compose
  - "*"
