#
# reference:
#   - https://lukasgeiter.github.io/mkdocs-awesome-nav/reference/
#

ignore: "*.hidden.md"

nav:
  - æ¦‚è¿°: index.md
  - "ğŸ“¦ é•œåƒåŠ é€Ÿ": mirrors.md
  - "GHCR.IO": ghcr.io.md
  - "*"
